_name_: pair_alignment
dataset_name: par_alignment
data_path: '/home/spadronalcala/Documents/thesis/hyena-dna-genome-similarity/data/pair_alignment'
max_length: 13370
d_output: 2
use_padding: True
padding_side: 'left'
add_eos: False
__l_max: ${.max_length}
shuffle: true  # set this as default!
